[book]
authors = ["Matheus Dias de Souza <hydroperfox@gmail.com>"]
language = "en"
multilingual = false
src = "src"
title = "MXMLExtrema Help"

[output.html]
copy-fonts = false
fold = { enable = true }