name: Build

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Log level'
        required: true
        default: 'warning'
        type: choice
        options:
        - info
        - warning
        - debug
      tags:
        description: 'Build'
        required: false
        type: boolean
      environment:
        description: 'Environment to run tests against'
        type: environment
        required: true

permissions:
  contents: write

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Install mdbook CLI
        run: cargo install mdbook --version ~0.4
      - name: Build book
        run: mdbook build
      - name: Git commit report
        run: |
          # https://unix.stackexchange.com/a/153863
          find . ! -name 'book' -type f -exec rm -rf {} +
          cp -r book ..
          rmdir --ignore-fail-on-non-empty book

          git init
          git remote add origin https://github.com/mxmlextrema/mxmlchelp
          git config --global user.name 'hydroperfox'
          git config --global user.email 'hydroperfox@gmail.com'
          git checkout -b live
          git rm --cached -r .
          git add .
          git commit -m "Automated report"
          git push origin -f live
