name: Build

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Log level'
        required: true
        default: 'warning'
        type: choice
        options:
        - info
        - warning
        - debug
      tags:
        description: 'Build'
        required: false
        type: boolean
      environment:
        description: 'Environment to run tests against'
        type: environment
        required: true

permissions:
  contents: write

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Install mdbook CLI
        run: cargo install mdbook --version ~0.4
      - name: Build book
        run: mdbook build
      - name: Git commit report
        run: |
          # https://stackoverflow.com/a/34057281/26380963
          shopt -s extglob
          rm -rf !(book)
          mv -f book .

          git config --global user.name 'hydroperfox'
          git config --global user.email 'hydroperfox@gmail.com'
          git switch -C live
          git rm --cached -r .
          git add .
          git commit -m "Automated report"
          git push origin -f live
